# Rolls whose effect clause came from a same-numbered bill in another session. Clauses written from each roll's own stored digest.
ROLL = {
 1109394: {"eff": 'which narrowed when long-sentence prisoners move from prison to supervision and put them on electronic monitoring'},
 1109471: {"eff": 'which narrowed when long-sentence prisoners move from prison to supervision and put them on electronic monitoring'},
 1111175: {"eff": 'which redrew the 105 Alabama House districts using the 2020 census'},
 1115491: {"eff": 'which redrew the 105 Alabama House districts using the 2020 census'},
 1643628: {"eff": 'the Gulf of America Act, which renames the Gulf of Mexico as the Gulf of America in Alabama law'},
 1318421: {"eff": "a bill to make it a felony to handle another person's absentee ballot or application"},
 1171971: {"eff": 'a bill to bar candidates and poll watchers from helping a voter cast a ballot'},
 1425650: {"eff": 'a bill to make a death caused by drunk driving murder or manslaughter in some cases'},
 1434894: {"eff": 'a bill to let prosecutors shut down a place that hands out material harmful to minors'},
 1566046: {"eff": 'which put hemp-made THC products such as delta-8 gummies under strict state control'},
 1566772: {"eff": 'which put hemp-made THC products such as delta-8 gummies under strict state control'},
 1350857: {"eff": "the House's own plan for redrawing Alabama's seven U.S. House districts after the Allen versus Milligan ruling"},
 1350910: {"eff": "the House's own plan for redrawing Alabama's seven U.S. House districts after the Allen versus Milligan ruling"},
 1432637: {"eff": 'a bill to let judges split prison sentences of up to 30 years, up from 20'},
 1614139: {"eff": "the Alabama Post-Election Audit Act, which makes each county audit one precinct's ballots after every general election"},
 1674032: {"eff": "the Alabama Post-Election Audit Act, which makes each county audit one precinct's ballots after every general election"},
 1300210: {"eff": 'the Deputy Brad Johnson Act, which cut the credit prisoners earn toward early release'},
 1404902: {"eff": "which made it a crime to be paid for handling another person's absentee ballot form"},
 1383756: {"eff": "which made it a crime to be paid for handling another person's absentee ballot form"},
 1694713: {"eff": "a backup plan for a new State Senate primary if a court restored Alabama's 2021 map too late"},
 1694623: {"eff": "a backup plan for a new congressional primary if a court restored Alabama's 2023 map too late"},
 1695918: {"eff": "a backup plan for a new congressional primary if a court restored Alabama's 2023 map too late"},
 1384609: {"eff": 'a bill to put county and city library boards under the direct control of the officials who appoint them'},
 1180303: {"eff": "the Alabama Lead Reduction Act, which rebuilt the state's lead paint program with required certification, training and exams"},
 1115493: {"eff": 'which redrew the eight State Board of Education districts using the 2020 census'},
 1180925: {"eff": 'a bill to add five to 20 mandatory years for carrying a gun during a violent crime'},
 1350905: {"eff": "which redrew Alabama's seven U.S. House districts after the Allen versus Milligan ruling, becoming Act 2023-563"},
 1316753: {"eff": "which requires Alabama's vote counting machines to use paper ballots the voter can inspect"},
 1573029: {"eff": 'which gave police officers a much stronger legal shield against lawsuits and charges'},
 1031548: {"eff": "a bill to create new crimes around protests with mandatory jail time"},
 1150547: {"eff": "a bill to create new crimes around protests with mandatory jail time"},
}
