# Rolls whose effect clause came from a same-numbered bill in another session (2025 regular s2173, Aug 2025 special s2224, 2026 s2243).
ROLL = {
 1599910: {"eff": 'which makes permanent the rule that high earners add back a federal business income deduction on their state taxes'},
 1599967: {"eff": 'which makes permanent the rule that high earners add back a federal business income deduction on their state taxes'},
 1662258: {"eff": 'which makes towns over 2,000 people allow homes on school, college and transit district land'},
 1661326: {"eff": 'which makes towns over 2,000 people allow homes on school, college and transit district land'},
 1654489: {"eff": 'which makes insurers check each year from 2027 that listed mental health providers are still in the network'},
 1627955: {"eff": 'which keeps the pandemic-era small business loan fund running for later problems and loosens its private match rule'},
 1688707: {"eff": 'which keeps the pandemic-era small business loan fund running for later problems and loosens its private match rule'},
 1693062: {"eff": 'which extends the tax credit for donations to child care centers through 2037'},
 1693108: {"eff": 'which lets the state name colleges thriving institutions for serving rural, low-income or first-generation students'},
 1692370: {"eff": 'which lets the state name colleges thriving institutions for serving rural, low-income or first-generation students'},
 1695572: {"eff": 'which adds an older-worker representative to the state workforce council'},
 1692805: {"eff": 'which adds an older-worker representative to the state workforce council'},
 1675632: {"eff": 'which bars pet stores from selling, leasing or auctioning dogs and cats from January 2028'},
 1672756: {"eff": 'which bars pet stores from selling, leasing or auctioning dogs and cats from January 2028'},
 1661323: {"eff": 'which lets landlords split one utility bill among tenants by formula, with no markup'},
 1658153: {"eff": 'which lets landlords split one utility bill among tenants by formula, with no markup'},
 1694758: {"eff": "which makes ride-hailing companies train every driver to carry a rider's service animal within six months of joining"},
 1696255: {"eff": "which makes ride-hailing companies train every driver to carry a rider's service animal within six months of joining"},
 1644217: {"eff": 'a bill to bar larger jurisdictions from requiring more than 2,000 square feet for a single family home lot'},
 1694959: {"eff": 'a bill to let marijuana hospitality businesses hold time-limited consumption events away from their own premises'},
 1695625: {"eff": 'which tells four state agencies to favor native plants on state land projects where workable'},
 1694687: {"eff": 'which tells four state agencies to favor native plants on state land projects where workable'},
 1697247: {"eff": 'which makes the state list host homes for adults with developmental disabilities'},
 1696240: {"eff": 'which makes the state list host homes for adults with developmental disabilities'},
 1566530: {"eff": 'which makes student career and academic plans include practice filling in a student aid application'},
 1697220: {"eff": 'which lets community solar gardens hold bill credits steady for low-income members'},
 1684217: {"eff": "which tells the state to write Colorado's Medicaid work rules with the least paperwork and post monthly approval figures"},
 1675686: {"eff": 'which makes preschool providers and the state keep child records private'},
 1697290: {"eff": 'which makes large transit agencies post clear maps, fares and discount rules from mid-2027'},
 1695916: {"eff": 'which makes large transit agencies post clear maps, fares and discount rules from mid-2027'},
 1696345: {"eff": 'a bill to cap the share of each fare ride-hailing companies keep at 20 percent'},
 1675727: {"eff": 'a bill to let a health service district add or drop affordable housing services without a major plan change'},
 1697843: {"eff": 'which defines coercive control, such as money control and tracking, for child custody cases'},
 1697569: {"eff": 'which defines coercive control, such as money control and tracking, for child custody cases'},
 1693615: {"eff": 'which makes the attorney general draft a plan to update police academy training'},
 1695567: {"eff": 'which lets someone harmed by conversion therapy sue the therapist with no time limit'},
 1693775: {"eff": 'which lets someone harmed by conversion therapy sue the therapist with no time limit'},
 1693760: {"eff": 'a bill to charge large employers a fee for workers kept under 30 hours who are on state Medicaid'},
 1675609: {"eff": 'which makes a person found not guilty by insanity prove they qualify for release'},
 1676686: {"eff": 'which makes a person found not guilty by insanity prove they qualify for release'},
 1507054: {"eff": 'a bill to excuse towns with fewer than 2,500 residents from adopting a home energy code'},
 1692028: {"eff": 'which lets the parole board, not the governor alone, grant early parole to young offenders in a special program'},
 1685552: {"eff": 'which lets the parole board, not the governor alone, grant early parole to young offenders in a special program'},
 1696058: {"eff": "which makes insurers count what a patient paid a pharmacy directly toward the patient's yearly cost cap from 2028"},
 1697449: {"eff": 'which sets a separate track for releasing body camera footage when police use of force kills someone'},
 1696212: {"eff": 'which sets a separate track for releasing body camera footage when police use of force kills someone'},
 1599933: {"eff": 'which pays clinics that also provide abortions, mainly Planned Parenthood, with state money after a federal Medicaid cutoff'},
 1599881: {"eff": 'which pays clinics that also provide abortions, mainly Planned Parenthood, with state money after a federal Medicaid cutoff'},
 1696980: {"eff": "which caps low-income households' gas and electric bills at two to six percent of income"},
 1697559: {"eff": "which caps low-income households' gas and electric bills at two to six percent of income"},
 1695653: {"eff": 'which phases out contractor-run child care licensing checks in favor of state specialists'},
 1599932: {"eff": 'which rewrites the November 2025 ballot question so high-earner tax money can also fund SNAP food aid'},
 1599888: {"eff": 'which rewrites the November 2025 ballot question so high-earner tax money can also fund SNAP food aid'},
 1696905: {"eff": 'which makes electric car battery suppliers take back used batteries and bans putting them in landfills'},
 1600086: {"eff": "which moves the start of the 2024 artificial intelligence bias law's duties from February 1 to June 30, 2026"},
 1667110: {"eff": 'which lets crisis workers and more school staff ask a court for an extreme risk protection order'},
 1621587: {"eff": 'which lets crisis workers and more school staff ask a court for an extreme risk protection order'},
 1694967: {"eff": "a bill to bar 16 and 17 year olds marrying someone over ten years older"},
 1697549: {"eff": "a bill to bar 16 and 17 year olds marrying someone over ten years older", "close": "The Colorado Senate agreed to those changes 18-17 but then rejected the bill 11-24, so it did not become law."},
 1695619: {"eff": 'a bill to let a person sue in state court over rights broken during civil immigration enforcement'},
 1642411: {"eff": 'a bill to let a person sue in state court over rights broken during civil immigration enforcement'},
 1641012: {"eff": 'which makes railroads, utilities and new factories in coal towns give former coal workers first shot at jobs'},
 1675896: {"eff": "which raises the income limit for first responder families' state-backed home loans to 110 percent of the usual cap"},
 1694961: {"eff": 'which bars insurers from making non-opioid pain drugs harder or costlier to get than opioids'},
 1665272: {"eff": 'a bill to make four second-generation rat poisons restricted-use pesticides from July 2027'},
 1537383: {"eff": 'which makes colleges set a clear process for disability reports and academic adjustments'},
}
