import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { readConfig, renderManifest } from "../../src/scripts/embedPilotManifest.js";

function writeConfig(value: unknown): string {
  const dir = mkdtempSync(path.join(tmpdir(), "embed-pilot-"));
  const file = path.join(dir, "embed-pilot.json");
  writeFileSync(file, JSON.stringify(value));
  return file;
}

const VALID_CITY = {
  slug: "austin-tx",
  name: "Austin",
  state: "tx",
  election_date: "2026-11-03",
  review_date: "2026-09-16",
  official_source_url: "https://www.sos.state.tx.us/elections/",
  enabled: true,
};

describe("readConfig", () => {
  it("accepts a valid config, upper-cases the state, and sorts publishers", () => {
    const config = readConfig(writeConfig({ publishers: ["zeta-news", "alpha-news"], cities: [VALID_CITY] }));
    expect(config.publishers).toEqual(["alpha-news", "zeta-news"]);
    expect(config.cities).toEqual([{ ...VALID_CITY, state: "TX" }]);
  });

  it("rejects a slug with upper-case letters or spaces", () => {
    expect(() => readConfig(writeConfig({ publishers: [], cities: [{ ...VALID_CITY, slug: "Austin TX" }] }))).toThrow(
      /slug "Austin TX"/
    );
  });

  it("rejects a publisher code that is not a slug", () => {
    expect(() => readConfig(writeConfig({ publishers: ["Austin Monitor"], cities: [] }))).toThrow(/publisher code/);
  });

  it("rejects duplicate slugs, bad dates, non-https sources, and a missing enabled flag", () => {
    expect(() => readConfig(writeConfig({ publishers: [], cities: [VALID_CITY, VALID_CITY] }))).toThrow(/duplicate slug/);
    expect(() =>
      readConfig(writeConfig({ publishers: [], cities: [{ ...VALID_CITY, election_date: "11/03/2026" }] }))
    ).toThrow(/YYYY-MM-DD/);
    expect(() =>
      readConfig(writeConfig({ publishers: [], cities: [{ ...VALID_CITY, official_source_url: "http://x" }] }))
    ).toThrow(/https/);
    expect(() => readConfig(writeConfig({ publishers: [], cities: [{ ...VALID_CITY, enabled: "yes" }] }))).toThrow(
      /enabled/
    );
  });
});

describe("readConfig states", () => {
  it("accepts two-letter state entries and rejects unknown codes or a collision with a city slug", () => {
    const state = { state: "tx", election_date: "2026-11-03", review_date: "2026-09-16", official_source_url: "https://www.sos.state.tx.us/", enabled: true };
    const config = readConfig(writeConfig({ publishers: [], cities: [VALID_CITY], states: [state] }));
    expect(config.states).toEqual([{ ...state, state: "TX" }]);
    expect(() => readConfig(writeConfig({ publishers: [], cities: [], states: [{ ...state, state: "zz" }] }))).toThrow(/not a two-letter US state code/);
    expect(() => readConfig(writeConfig({ publishers: [], cities: [{ ...VALID_CITY, slug: "tx" }], states: [state] }))).toThrow(/collide/);
  });
});

describe("renderManifest", () => {
  it("emits a TypeScript module keyed by slug with the resolved district ids", () => {
    const source = renderManifest(
      ["alpha-news"],
      [{ ...VALID_CITY, state: "TX", kind: "city", district_ids: ["11111111-1111-4111-8111-111111111111"] }]
    );
    expect(source).toContain("GENERATED by `npm run embed:pilot-manifest`");
    expect(source).toContain('export const EMBED_PILOT_PUBLISHERS: readonly string[] = [\n  "alpha-news"\n];');
    expect(source).toContain('"austin-tx": {');
    expect(source).toContain('"district_ids": [\n      "11111111-1111-4111-8111-111111111111"\n    ]');
    expect(source).toContain('"kind": "city"');
  });

  it("renders empty collections when nothing is configured", () => {
    const source = renderManifest([], []);
    expect(source).toContain("EMBED_PILOT_PUBLISHERS: readonly string[] = [];");
    expect(source).toContain("EMBED_PILOT_CITIES: Readonly<Record<string, EmbedPilotCity>> = {};");
  });
});
