TRIMP = {
 "which makes it permanently unlawful in California to kill": "which permanently bans killing or capturing birds protected under federal law as of 2025",
 "which lets small housing projects in historic districts": "which fast-tracks small housing projects in historic districts unless the building itself is historic",
 "which puts the management companies and investors": "which puts companies and investors behind medical practices under the state health cost watchdog",
 "which sets a physical fit test": "which sets a physical fit test from 2027 for riding without a booster seat",
 "which regulates companies that advance lawsuit money": "which regulates companies that advance lawsuit money for a cut of the payout",
 "which makes hospitals check from July 2027": "which makes hospitals check from 2027 whether patients qualify for free or discounted care",
 "which lets state tax-exempt status count": "which lets state tax-exempt status count wherever state law looks at federal tax-exempt status",
 "which lets rideshare drivers form an organization": "which lets rideshare drivers organize and bargain with the companies over pay and conditions",
 "which lets a court's fix for illegal local election rules": "which lets a court's fix for illegal local election rules apply during an appeal",
 "which makes police and prosecutors adopt rules": "which requires rules by 2027 for interviewing the family of someone an officer killed",
 "which makes price-fixing cases easier": "which makes price-fixing cases easier to bring when the facts plausibly show a conspiracy",
 "which bars gun dealers from July 2026": "which bars gun dealers selling pistols easily converted to machine guns from July 2026",
 "which lets defendants claiming racial bias": "which lets defendants claiming racial bias get all the evidence bearing on that claim",
 "which widens the right to see evidence after conviction": "which widens post-conviction access to evidence to any felony with a state prison sentence",
 "which lets adults change their name": "which lets adults change their name to match their gender identity without a hearing",
 "which widens what a state grant fund": "which widens what a state grant fund for transgender and intersex people can fund",
 "the Family Preparedness Plan Act": "which lets more relatives enroll a child in school and approve school medical care",
 "which lets tenants facing eviction": "which lets tenants facing eviction cite a Social Security payment break as a defense",
 "which makes it illegal to trade in wildlife": "which bans trading in wildlife taken in breach of the protections of January 2025",
 "which makes a working stove and refrigerator": "which makes a working stove and refrigerator required in rented homes from 2026",
 "which makes schools and colleges print an LGBTQ+ crisis line": "which makes schools and colleges print an LGBTQ+ crisis line on student ID cards",
 "which keeps emergency water flow rules": "which keeps emergency water flow rules for the Scott and Shasta rivers until 2031",
 "which lets people who provide immigration support services": "which lets immigration support workers keep their home address private from October 2027",
 "a bill to pay for counseling": "a bill funding counseling for young gun violence survivors in Los Angeles County",
 "known as Lindalee's Law": "Lindalee's Law, a bill putting the Attorney General in charge of watching how health plans run forced arbitration",
 "which counts policies that keep people housed": "which counts policies keeping people housed when the state rates a city's housing support",
 "which bars public agencies from passing on retired diesel": "which bars passing on retired public diesel rail equipment unless it meets cleaner standards",
 "which makes police reports written with artificial intelligence": "which makes police reports written with artificial intelligence say so and carry a signature",
 "which orders model rules by July 2026": "which orders model rules by July 2026 on how agencies deal with immigration authorities",
 "which shields medical records from other states' cases": "which shields medical records from other states' cases over care legal in California",
 "which bars local laws that punish people for helping the homeless": "which bars local laws punishing people for giving the homeless food, water or shelter",
 "which sets up a state bureau to verify descent": "which sets up a state bureau to verify descent from enslaved Americans for reparations",
 "which makes it state policy that every home": "which makes it state policy that every home can reach a safe indoor temperature",
 "the California Combating Auto Retail Scams Act": "the Combating Auto Retail Scams Act, which tightens rules against deceptive car dealer pricing",
 "which makes it a crime for officers, including federal agents, to hide": "which makes it a crime for officers, including federal agents, to mask their faces",
 "which makes plainclothes officers": "which makes plainclothes officers, federal ones included, show their agency and badge number",
 "which sets up a program paying nonprofits": "which creates a program, once funded, paying nonprofits to teach low-wage workers their rights",
 "a bill to fine large social media companies": "a bill fining large social media companies whose recommendation systems break civil rights laws",
 "which keeps court records private for people of any age": "which keeps court records private for anyone changing their name or gender marker",
 "which raises the top antitrust fine": "which raises the top company antitrust fine from $1 million to $6 million",
 "the Transparency in Frontier Artificial Intelligence Act": "which sets safety duties for companies training the largest artificial intelligence models",
 "the California Fair Elections Act": "which lifts the ban on public money for candidates who accept spending limits",
 "the Workplace Know Your Rights Act": "which makes employers hand every worker a yearly notice of workplace rights",
 "which bars police from interfering with elections": "which bars police interfering with elections or touching voter lists without a court order",
 "a bill to make gun serial-number tampering": "a bill making gun serial-number tampering convictions cost the right to own guns",
 "a bill to apply medical privacy law to health chatbots": "a bill applying medical privacy law to health chatbots and keeping a licensed person in charge of clinical decisions",
 "a bill to strengthen the rules on keeping election materials": "a bill strengthening rules on keeping election materials until any contest is decided",
}
