TRIMP = {
 "which gives criminal defendants the right to inspect": "which lets criminal defendants inspect police-held physical evidence at least 35 days before trial",
 "which bars urban local rules": "which bars urban local rules cutting housing density or uses below their July 2025 zoning",
 "which lets fire districts require property owners": "which lets fire districts make property owners clear dead or dry plants that carry wildfire",
 "a bill to bar card networks": "a bill barring card networks from charging swipe fees on the sales tax or tip part of a bill",
 "which makes gun show promoters": "which makes gun show promoters file a security plan with police and carry liability insurance",
 "which lets people apply for state vocational rehabilitation": "which lets people apply for state vocational rehabilitation services from outside Colorado",
 "which lets the governor declare an emergency": "which lets the governor declare a market-disruption emergency and call steep price rises gouging",
 "which bars the state from demanding a social security number": "which bars demanding a social security number from people applying for utility bill help",
 "which makes home insurers share their wildfire risk models": "which makes home insurers share wildfire risk models and credit homeowners who cut risk",
 "which bans decorative grass": "which bans decorative grass at new homes in 12-unit-plus developments from 2028",
 "which requires water district tap fees": "which requires water district tap fees to reasonably match the cost of providing service",
 "which makes a homeowners association follow": "which makes homeowners associations follow their bylaws and state law before collecting from owners",
 "a bill to cap city court jail terms": "a bill capping city court jail terms at what state law allows",
 "which makes it illegal to threaten or scare": "which bans threatening or scaring anyone for voting, helping others vote or running an election",
 "which widens the remedies for discrimination": "which adds legal fees and a choice of payouts for discrimination in public places",
 "which gives people in state prisons a right to social visits": "which gives state prisoners a right to social visits, phone calls and video calls",
 "which sets up an automated system": "which sets up automatic notices of the dates and terms of protection orders",
 "which sends some county board vacancies": "which fills some larger-county board vacancies by election instead of a party committee",
 "which makes statewide ballot measure titles": "which makes statewide ballot measure titles describe fiscal impact and bars repeat draft filings",
 "which makes landlords return security deposits": "which makes landlords return security deposits within 30 days and show receipts for money kept",
 "which limits pharmacy benefit managers": "which limits pharmacy benefit managers to a flat fee per prescription, not drug-price-based pay",
 "which strengthens wage theft enforcement": "which strengthens wage theft enforcement and counts quarter-owners of a company as employers",
 "which makes large cities allow buildings": "which makes large cities allow five-story buildings with a single stairway by December 2027",
 "which refocuses the youthful offender system": "which refocuses the youthful offender system on treatment, with a case manager for everyone",
 "which makes it a crime to 3-D print": "which criminalizes 3-D printing or milling a working gun or gun part without a license",
 "which makes hospitals give every birthing parent": "which makes hospitals give every birthing parent written notice of their right to respectful care",
 "which lets cities put property tax growth": "which lets cities use property tax growth on old mines and landfills for renewable energy",
 "which pushes utilities to use better wire": "which pushes utilities toward wire and tools that carry more power on existing lines",
 "which requires a cancer or birth defect warning label": "which requires cancer or birth defect warnings on hair relaxers and hairpieces from 2027",
 "which makes counties sell a tax lien": "which has counties sell tax liens on mobile homes rather than seize them",
 "which makes app stores ask a user's age": "which makes app stores ask a user's age at account setup and pass it to apps from July 2028",
 "a bill to create a Colorado Worker Safety Act": "a bill creating a Colorado Worker Safety Act with a state duty to keep workplaces free of known hazards",
 "which makes employers of 100 or more": "which makes employers of 100 or more report staff by race and sex from 2027",
 "which softens the tax-cut warning": "which softens the tax-cut warning in ballot measure titles to say funding likely falls",
 "a bill to ban setting a price or wage": "a bill banning prices or wages set per person from data gathered about them",
 "which widens how students can earn a seal of biliteracy": "which widens the seal of biliteracy and adds a lower seal for speaking and listening",
 "which makes public chatbot operators": "which makes chatbot operators check for child users and owe children extra duties",
 "which spells out how the ban on unfair treatment": "which spells out how the public-places anti-discrimination ban applies to schools and colleges",
 "which adds a state income tax credit for families": "which adds a state child tax credit from 2027, paid for by taxing software",
 "a bill to void arbitration clauses": "a bill voiding arbitration clauses that charge workers or shoppers fees far above court fees",
 "which makes the state publish a model plan": "which orders a model plan for protecting workers from extreme heat and cold by 2028",
 "which lets the state reinvest its sales tax growth": "which lets the state reinvest sales tax growth near transit stations into sidewalks and crossings",
 "which bans making, selling or buying most detachable-magazine": "which bans most detachable-magazine semiautomatic rifles unless the buyer passes a safety course",
 "which strengthens the shield for abortion": "which strengthens the shield for abortion and gender-affirming care, including clinic-only pill labels",
 "which lets the state treasurer invest": "which lets the state invest up to $50 million in bonds for affordable for-sale homes",
 "which orders regional building codes": "which orders regional building codes for factory-built homes, which cost less than site-built homes",
 "which gives parents of newborns in intensive care": "which gives parents of newborns in intensive care up to 12 more weeks' paid leave",
 "which lets gun dealers ask police": "which lets gun dealers get a police serial-number check before a private-seller purchase",
 "which creates the Colorado Voting Rights Act": "which creates the Colorado Voting Rights Act, barring local election rules that weaken minority voters",
 "which makes the state run the free birth certificate": "which makes the state itself run the free birth certificate and ID program from 2027",
 "which lets people who post bail": "which lets bailed people stay overnight so jail staff can link them to services",
 "which lets the state fine retailers": "which lets the state fine retailers up to $5,000 a day over substandard gasoline",
 "which writes into state law a hospital's duty": "which writes into state law a hospital's duty to examine and stabilize emergency patients",
 "which makes the state watch center": "which makes the state watch center tell rail regulators at once about reported train emergencies",
 "which cuts the Denver transit board": "which cuts the Denver transit board to five elected seats plus four governor appointees",
 "which lets a homeowner ask a court for access": "which lets homeowners seek court access to a neighbor's land to repair a shared wall",
 "which triggers prison overcrowding steps": "which triggers prison overcrowding steps at four percent vacancy and widens who gets told",
 "which lets prisoners aged 60 or over": "which lets prisoners 60 or over with 20 years served ask for a sentence review",
 "which creates an insurer-funded grant program": "which creates an insurer-funded grant program to harden homes against hail, wind and wildfire",
 "which makes building permit applicants": "which makes permit applicants on jobs over $1 million swear every worker has injury insurance",
}
ROLL = {1600103: {"close": "The Colorado House accepted those changes 41-20 in the August 2025 special session, and the governor signed it into law."}}
