TRIMP = {
 "which bars utilities from shutting off a home's power": "which bars utilities shutting off a home's power or gas over the holidays or on freezing or extreme-heat days",
 "the Freedom to Read Act": "the Freedom to Read Act, barring public and school libraries from pulling books over their author or ideas",
 "which requires permits and inspections for disabled parking": "which requires permits and inspections for disabled parking spaces and raises the illegal parking fine from $200 to $250",
 "which lets a public employee union be certified": "which lets a public employee union be certified without an election once over half the workers sign cards",
 "which requires rental homes built before 1978": "which requires rental homes built before 1978 to pass a lead paint inspection, with state help for landlords",
 "which rewrites Delaware's parentage law": "which rewrites Delaware's parentage law to define a child's legal parents the same way whatever their gender or marital status",
 "which removes the dollar caps and the $50,000 price limit": "which removes the dollar caps and $50,000 price limit on Delaware's electric car rebates, letting the state set amounts",
 "which requires a state license for people who flip": "which requires a state license to flip home purchase contracts and gives sellers 21 days to cancel such a deal",
 "which writes the state Office of Gun Violence Prevention": "which writes the Office of Gun Violence Prevention and Community Safety into law so a future governor cannot undo it",
 "which gives owners of untraceable ghost guns": "which gives owners of untraceable ghost guns six months to get a serial number stamped on or disable them",
 "which enrolls new state workers in a retirement savings plan": "which enrolls new state workers in a retirement savings plan by default unless they opt out",
 "the Delaware John Lewis Voting Rights Act": "the John Lewis Voting Rights Act, which lets voters sue over rules that hold back minority voters",
 "which lets 16- and 17-year-olds target shoot": "which lets 16- and 17-year-olds shoot and hunt without an adult present after a hunter safety course, with parental permission",
 "which makes hospitals give free medically necessary care": "which makes hospitals give free medically necessary care to Delaware residents earning up to three times the poverty level",
 "which makes data centers and other very large power users pay": "which makes data centers and other very large power users pay their own hookup and rate costs",
 "which takes Delaware's job-creation tax break away": "which denies the job-creation tax break to data centers and other very large power users not running on clean energy",
 "which lets courts order a person found dangerous": "which lets courts make a person found dangerous give up their guns for up to five years, up from one",
 "which makes school breakfast free": "which makes school breakfast free for every student at public schools in the federal breakfast program",
}
