TRIMP = {
 "the Eddie Thomas Act": "the Eddie Thomas Act, which makes state prisons publish a yearly report on hospice and end-of-life care",
 "which requires police to trace every crime gun": "which requires police to trace every crime gun through the federal eTrace system and share the results",
 "which lets a university and its employees' union": "which lets a university and its employees' union agree contract terms giving workers more rights than civil service rules",
 "which lets a child wrongly named as a defendant": "which lets a child wrongly named in an eviction case recover attorney fees and $1,000 in damages",
 "which requires health professionals to take an hour": "which requires health professionals to take an hour of hidden-bias training to renew a license",
 "which lets a person tell a collection agency": "which lets a person tell a collection agency in writing that a debt was coerced",
 "which lets the Department of Natural Resources use rewilding": "which lets the Department of Natural Resources use rewilding, returning land to its natural state with native species",
 "which lets a person with a protective order": "which lets a person with a protective order against a parole candidate submit a victim statement",
 "which requires health plans issued after January 1, 2027 to cover equine": "which requires health plans issued from 2027 to cover equine therapy when a doctor says it is needed",
 "which bars notaries from charging a fee": "which bars notaries charging a fee to notarize the form a homeless person uses to get a state ID",
 "which requires employers to enroll every worker": "which requires employers to enroll every worker of 120 days or more in the state's Secure Choice retirement program",
 "which raises the fee for employers that underpay": "which raises the fee for employers that underpay workers and makes final Labor Department orders enforceable like court judgments",
 "which makes the Office of Firearm Violence Prevention report": "which makes the Office of Firearm Violence Prevention report where gun violence is concentrated and what is spent there",
 "which creates a task force on how flooding": "which creates a task force on how climate damage pushes Illinois residents from their homes",
 "which requires gun owners to lock guns away": "which makes gun owners lock guns away from minors and at-risk people and report lost guns within 48 hours",
 "which requires companies that hold or trade cryptocurrency": "which makes companies holding or trading cryptocurrency for Illinois residents register with the state",
 "which stops state agencies from weakening": "which stops state agencies weakening worker-pay or coal-mine safety rules below the federal protections of April 2025",
 "which makes local officials weigh traffic pollution": "which makes local officials weigh pollution on nearby communities before approving a waste facility",
 "which requires health plans issued after January 1, 2027 to cover medically necessary laser": "which requires health plans issued from 2027 to cover medically necessary laser hair removal",
 "which requires every public college to give students access to at least three": "which makes every public college offer students at least three licensed mental health professionals",
 "which requires public colleges to give students access to providers": "which makes public colleges give students access to prescribers of birth control and medication abortion",
 "which bans cosmetics, dental floss": "which bans cosmetics, dental floss, children's and menstrual products and underwear with added PFAS",
 "which makes health insurers keep reporting": "which keeps insurers reporting premium spending on claims and paying refunds if federal rules end",
 "which creates a State Public Defender Commission": "which creates a commission to plan a statewide Office of the State Public Defender",
 "which lets regulators approve low-income discounts": "which lets regulators approve low-income discounts covering a whole utility bill, funded by a charge on other customers",
 "which suspends the license of drivers with two speeding offenses": "which suspends drivers with two speeding offenses in a year unless they drive with a speed-limiting device",
 "which bars the state from delaying a barber": "which bars the state delaying a barber, cosmetology or nail technology license application because the applicant is in prison",
 "which requires health plans from 2028 to cover up to a six-month supply": "which makes health plans cover six-month supplies of prescribed hormone therapy from 2028",
 "which guarantees full gross pay for up to a year": "which guarantees full pay for up to a year to police, firefighters, paramedics and prison staff hurt on duty",
 "the Illinois Hemp Act": "the Illinois Hemp Act, requiring a license to make or sell hemp products and letting the state order recalls",
 "the SECURE Act": "the SECURE Act, making the child welfare agency guard records showing a child's sexual orientation",
 "which requires adult changing tables": "which requires adult changing tables and accessible restrooms in certain new public buildings from 2029",
 "which bars car insurers from raising a renewal premium": "which bars car insurers raising a renewal premium over 10% without 30 days' notice",
 "which lets a public defender also represent a client": "which lets a public defender also handle a client's license suspension case arising from the same arrest",
 "which makes rules that unfairly harm protected groups": "which makes rules that unfairly harm protected groups a civil rights violation",
 "which requires a detailed written warning": "which requires a detailed written warning, a chance to respond and arbitration rights before a tenured teacher's dismissal",
 "which requires high school CPR training": "which requires high school CPR training to use manikins with breasts as well as without, from 2029",
 "which caps rental application fees at $50": "which caps rental application fees at $50 and voids unlisted landlord fees",
 "which lets Medicaid patients bring a Medicaid doula": "which lets Medicaid patients bring a Medicaid doula to childbirth, among other Medicaid changes",
 "which requires crypto cash machine operators": "which makes crypto cash machine operators register with the state, cap fees and warn users",
 "which lets rideshare drivers organize and bargain": "which lets rideshare drivers organize and bargain as a group with the companies, funded by a per-trip fee",
 "which raises the training required to work as a school psychologist": "which raises school psychologist training to a 60-hour graduate degree and 1,200 supervised hours",
}
ROLL = {1582161: {"open": ("Voted to pass House Bill 460", "Voted against passing House Bill 460"), "eff": "which extends state aid at city and county colleges to residents barred from federal aid, including undocumented students"}}
