TRIMP = {
 "a bill to make every food business post allergen": "a bill making every food business post allergen information for staff and tell customers which allergens menu items contain",
 "a bill to double the criminal fines": "a bill doubling criminal fines for breaking the child labor law, to $1,000 for a first violation and $3,000 after",
 "a bill to bar insurers from capping": "a bill barring insurers from capping yearly or lifetime payouts for core benefits if the federal protection is repealed",
 "a bill to bar insurers from denying coverage": "a bill barring insurers from denying coverage or charging more for a pre-existing condition if the federal protection is repealed",
 "a bill to make the state write workplace safety standards": "a bill making the state write workplace safety standards for public employers, matching what federal law asks of private ones",
 "a bill to let a town deny a permit": "a bill letting a town deny permits to a company with unpaid taxes, unpaid bills or serious code violations",
 "a bill to let counties adopt and enforce": "a bill letting counties adopt and enforce property maintenance codes, with state grants of up to $100,000 per town",
 "a bill to let a town hand a long-abandoned": "a bill letting a town hand a long-abandoned, blighted property to a land bank that returns vacant property to use",
 "a bill to raise the realty transfer tax money": "a bill raising the realty transfer tax share for the state housing affordability fund to $110 million a year",
 "a bill to extend the equal pay law": "a bill extending the equal pay law to race and ethnicity and protecting workers who discuss pay",
 "a bill to make every hospital, nursing home": "a bill making every hospital, nursing home and other health care site run a program to prevent violence against staff",
 "a bill to allow shared community solar projects": "a bill allowing community solar projects, letting people subscribe to a shared site and get credit on their electric bill",
 "a bill to create a public registry of owners": "a bill creating a public registry of owners with serious property code violations left unfixed for a year",
 "a bill to create Keystone Saves": "a bill creating Keystone Saves, automatically enrolling workers with no retirement plan at work in a state-run savings account",
 "a broad election code rewrite": "an election code rewrite creating in-person early voting and requiring at least two ballot drop boxes in every county",
 "a bill to let towns spend some tax increment financing": "a bill letting towns spend some tax increment financing money on keeping current residents from being pushed out",
 "a bill to make health insurers, Medicaid, and the state children's health plan cover birth control": "a bill making insurers, Medicaid and the children's health plan cover birth control and sterilization at no cost",
 "which makes every county keep a contact list": "which makes every county keep a contact list for absentee-owned property so code violations reach someone who can fix them",
 "a bill to ban driveway and parking lot sealants": "a bill banning driveway and parking lot sealants high in PAH chemicals, with fines of up to $2,500 per violation",
 "a bill to open a two-year window": "a bill opening a two-year window for adults abused as children to sue even though the normal deadline has passed",
 "a bill to extend the prevailing wage law to HVAC duct cleaning": "a bill extending the prevailing wage law to HVAC duct cleaning and off-site custom work and banning split pay rates",
 "a bill to let the treasurer return unclaimed property": "a bill letting the treasurer return unclaimed property under $10,000 to its owner without a claim",
 "a bill to cap yearly lot rent increases": "a bill capping yearly lot rent increases in manufactured home communities at the inflation rate, between 2% and 4%",
 "a bill to make health insurers cover a blood pressure monitor": "a bill making health insurers cover a blood pressure monitor for pregnant and postpartum patients when a doctor orders one",
 "a bill to let the revenue department share tax data": "a bill letting the revenue department share tax data with labor offices investigating employers who misclassify workers as contractors",
 "a bill to raise the minimum wage from $7.25 to $12": "a bill raising the minimum wage from $7.25 to $12 to $15 an hour by 2028, depending on the county",
 "a bill to raise the share of state sales tax for public transit from 4.4% to 7.9%": "a bill raising the transit share of state sales tax from 4.4% to 7.9%, plus $500 million for roads",
 "a bill to set one set of rules for who counts as a child's legal parent": "a bill setting one rule for who counts as a child's legal parent, whatever the parents' marital status or gender",
 "a bill to hide old eviction filings": "a bill hiding old eviction filings from public court records after seven years, or right away if the tenant won",
 "a bill to make event tickets": "a bill making event tickets, hotel rooms and food delivery show the full price with all mandatory fees up front",
 "a bill to let towns use public money and crews": "a bill letting towns use public money and crews to fix private water and sewer lines to protect public health",
 "a bill to free drivers from early termination penalties": "a bill freeing drivers from lease early-termination penalties when the state pulls their license for medical reasons",
 "a bill to expand the child and dependent care tax credit": "a bill expanding the child and dependent care tax credit, including for taxpayers using a dependent care program at work",
 "a bill to stop health insurers refusing to cover mental health care": "a bill stopping insurers refusing mental health care or speech therapy coverage just because a student got it at school",
 "a bill to seek federal permission for food stamp and WIC recipients": "a bill seeking federal permission for food stamp and WIC recipients to buy diapers and period products with their benefits",
 "a bill to cap bank overdraft": "a bill capping bank overdraft and insufficient funds fees at $15 and limiting them to three a day",
 "which makes pharmacists tell customers a drug's price": "which makes pharmacists tell customers a drug's price on request and lets ambulance crews hand naloxone to family or friends",
 "a bill to make Medicaid and the state children's health plan cover a home blood pressure monitor": "a bill making Medicaid and the children's health plan cover a home blood pressure monitor for pregnant and postpartum patients",
 "a bill to make hotels with 100 or more rooms": "a bill making hotels of 100 or more rooms give employees working alone in guest rooms a free safety device",
 "a bill to create a state false claims law": "a bill creating a false claims law making anyone who defrauds the state pay triple the loss plus a penalty",
 "a bill to raise the share of state sales tax going to public transit from 4.4% to 6.15%": "a bill raising the transit share of state sales tax from 4.4% to 6.15%, plus a road and bridge fund",
 "a bill to make it a felony to make, sell, or own an undetectable gun": "a bill making it a felony to make, sell or own a gun that metal detectors cannot find",
 "a bill to create red flag orders": "a bill creating red flag orders letting a judge take guns from someone found to be a serious risk",
 "a bill to ban machine gun conversion devices": "a bill banning machine gun conversion devices, with up to five years in prison for making, selling or owning one",
 "a bill to let people see, correct, and delete": "a bill letting people see, correct and delete personal data companies hold and opt out of targeted ads",
 "a bill to make companies report a data breach": "a bill making companies report a data breach as soon as they discover it, including readable encrypted data",
 "a bill to create a right to repair": "a right-to-repair bill making manufacturers sell repair shops and owners the manuals, parts and tools to fix their equipment",
 "which sets up a state list of nicotine vapes": "which sets up a state list of nicotine vapes that may be sold, with yearly certification and a $50,000 bond",
 "a bill to let experienced pharmacy technicians": "a bill letting experienced pharmacy technicians register without a diploma and letting the CDC set pharmacists' vaccination rules",
 "a bill to make employers write down their harassment": "a bill making employers write down their harassment, discrimination and retaliation policies, with fines of $500 to $5,000",
 "a bill to expand the state energy efficiency program": "a bill expanding the state energy efficiency program and raising the share of its money allowed for pilots to 5%",
 "a bill to let a court shorten the prison term": "a bill letting a court shorten the prison term of someone terminally ill or too ill or frail for self-care",
 "a bill to make assault, stalking, harassment": "a bill making assault, stalking, harassment and similar crimes one level more serious when the offender broke a protective order",
 "a bill to set minimum energy and water efficiency standards": "a bill setting minimum energy and water efficiency standards for appliances, faucets, showerheads, toilets and similar products",
 "a bill to set tougher sentences for threatening a school": "a bill setting tougher sentences for threatening a school or college and making offenders repay the emergency response cost",
 "a bill to make meat packing and food processing plants": "a bill making meat packing and food processing plants of 100 or more workers run joint safety committees",
 "a bill to raise the minimum wage from $7.25 to $15": "a bill raising the minimum wage from $7.25 to $15 an hour by 2029, then tying it to living costs",
 "a bill to create a state paid family and medical leave program": "a bill creating state paid family and medical leave funded by payroll contributions of up to 1% of wages",
 "a bill to set rail safety rules": "a rail safety bill: two-person crews, a train length limit and $10,000 fines for blocking crossings against emergency vehicles",
 "a bill to have the state write a model zoning ordinance": "a bill having the state write a model zoning ordinance for data centers covering size, noise, water use and emergencies",
 "a bill to make schools publish mental health warning-sign guidance": "a bill making schools publish mental health warning-sign guidance and tell families twice a year what services are available",
 "a bill to require a fuel gas detector": "a bill requiring a fuel gas detector in rooms with a gas-burning appliance when a home is sold or re-rented",
 "a bill to cap at $200": "a bill capping at $200 what a patient can be charged for an electronic copy of their own medical records",
 "a bill to let the state regulate and require permits for water": "a bill letting the state regulate and permit water use by data centers drawing more than 100,000 gallons a day",
 "which makes schools with sports teams keep a defibrillator": "which makes schools with sports teams keep a defibrillator at games and practices and plan for cardiac emergencies",
 "a bill to let a tenant who is a victim of violence": "a bill letting a violence victim break a lease early, change the locks and be shielded from landlord retaliation",
 "a bill to allow one accessory dwelling unit": "a bill allowing one accessory dwelling unit, such as a basement apartment or backyard cottage, wherever a home is allowed",
 "a bill to let the state route the tax filings": "a bill routing the tax filings of businesses owing over $5,000 in overdue sales tax through a third party",
 "a bill to stop towns from capping how many people": "a bill stopping towns from capping how many people can share a home based on family relationship",
 "a bill to make electric utilities publish maps": "a bill making electric utilities publish maps every two months of where the grid can take new solar and batteries",
 "a bill to make electric utilities run virtual power plant programs": "a bill making electric utilities run virtual power plant programs linking home batteries and solar panels to support the grid",
 "a bill to require a clear label on ads": "a bill requiring a clear label on ads using artificial intelligence to create or heavily alter images, video or audio",
 "a bill to end the automatic life sentence": "a bill ending automatic life for second-degree murder, setting a minimum of at least 35 years and opening parole",
 "a bill to deny unemployment benefits": "a bill denying unemployment benefits to a claimant who discourages their own hiring, such as by skipping an interview",
 "a bill to make prosecutors report a defendant": "a bill making prosecutors report a defendant to federal immigration officers whenever they suspect the person is not a citizen",
 "a bill to bar releasing a defendant without cash bail": "a bill barring release without cash bail once a judge finds a defendant is a threat to public safety",
 "a bill to make threatening a school or college a felony": "a bill making threatening a school or college a felony and making offenders pay the emergency response cost",
 "a bill to set a 10-year mandatory minimum": "a bill setting a 10-year mandatory minimum for deadly drug sales by sellers with two or more prior drug convictions",
 "a bill to bar transgender girls and women from women's sports teams at public schools": "a bill barring transgender girls and women from women's sports teams at public schools and colleges",
 "a bill to make it a felony to destroy, hide, or alter a public record": "a bill making it a felony to destroy, hide or alter a public record someone has requested",
 "a bill to require a fresh review of any regulation": "a bill requiring a fresh review of any regulation costing over $1 million a year after three years",
 "a bill to stop towns from blocking utility hookups": "a bill stopping towns blocking utility hookups by energy type, ending local bans on new natural gas connections",
 "a bill to tighten how abandoned oil and gas wells": "a bill tightening abandoned oil and gas well sealing, requiring a confirmed cement plug at least 50 feet long",
 "a bill to place medical, nursing, and dental students": "a bill placing medical, nursing and dental students in rotations at rural and community health clinics, with federal stipends",
 "a bill to bar transgender girls and women from women's school and college sports teams": "a bill barring transgender girls and women from women's school and college sports teams, with a right to sue",
 "a bill to void all local gun and ammunition rules": "a bill voiding all local gun and ammunition rules and letting anyone harmed by one sue the town",
 "a bill to extend the prevailing wage law to off-site custom fabrication": "a bill extending the prevailing wage law to off-site custom fabrication while dropping small residential rehabs and duct cleaning",
 "a bill to make the state tell eligible older adults": "a bill making the state tell eligible older adults about the LIFE program that helps frail seniors stay home",
 "a bill to replace the automatic life sentence": "a bill replacing the automatic life sentence for second-degree murder with a court-set minimum of at least 35 years",
}
