# Federal rolls: roll numbers repeat across Congresses, so ROLL keys are "chamber:session:roll".
TRIMP = {
 "which added sexual orientation and gender identity": "which added sexual orientation and gender identity to the categories protected from discrimination in jobs, housing, credit, education and public accommodations",
 "the Protecting America's Wilderness and Public Lands Act": "the Protecting America's Wilderness and Public Lands Act, designating new wilderness, conservation and recreation areas on federal land in eight states",
 "which restricted chokeholds and no-knock warrants": "which restricted chokeholds and no-knock warrants, made it easier to sue officers for misconduct, and set national police standards",
 "the PRO Act": "the PRO Act, a bill to strengthen workers' right to unionize, bar permanently replacing strikers and override state right-to-work laws",
 "the Bipartisan Background Checks Act": "the Bipartisan Background Checks Act, a bill requiring a background check on nearly every private gun sale, including at gun shows",
 "the Enhanced Background Checks Act": "the Enhanced Background Checks Act, a bill giving dealers at least ten business days, up from three, for a background check",
 "the American Dream and Promise Act": "the American Dream and Promise Act, offering green cards to immigrants brought here as children and others under temporary protection",
 "the Farm Workforce Modernization Act": "the Farm Workforce Modernization Act, which created legal status and a path to permanent residence for undocumented farmworkers",
 "the Paycheck Fairness Act": "the Paycheck Fairness Act, narrowing employers' defenses for paying men and women differently and protecting workers who discuss pay",
 "the NO BAN Act": "the NO BAN Act, which limited the President's power to bar entry and barred religious discrimination in immigration decisions",
 "the Access to Counsel Act": "the Access to Counsel Act, guaranteeing citizens, green card and visa holders a lawyer when held for extra border screening",
 "the Fairness in Orphan Drug Exclusivity Act": "which limited seven years of sole-sales rights for rare-disease drugs to those not expected to make a profit",
 "the Comprehensive Debt Collection Improvement Act": "the Comprehensive Debt Collection Improvement Act, which restricted debt collection practices and extended student loan protections to private loans",
 "a bill to let workers win an age discrimination claim": "a bill letting workers win an age discrimination claim by showing age was a motivating factor, not the sole cause",
 "a bill to restore the Federal Trade Commission's power": "a bill restoring the Federal Trade Commission's power to seek court-ordered refunds from companies engaged in fraud or false advertising",
 "which directed the federal environmental agency to label": "which directed the EPA to label long-lasting PFAS chemicals hazardous, set drinking water limits and fund cleanup of contaminated sites",
 "the John R. Lewis Voting Rights Advancement Act": "the John R. Lewis Voting Rights Advancement Act, restoring federal approval of voting changes in places with a record of discrimination",
 "the National Defense Authorization Act for Fiscal Year 2022": "the National Defense Authorization Act for Fiscal Year 2022, which set defense policy and approved Defense Department programs and military construction",
 "the Women's Health Protection Act, a bill": "the Women's Health Protection Act, creating a federal right to abortion care and barring state restrictions such as waiting periods",
 "the PUMP for Nursing Mothers Act": "the PUMP for Nursing Mothers Act, extending break time and a private space to pump breast milk to salaried workers",
 "the Family Violence Prevention and Services Improvement Act": "which renewed and expanded federal funding for emergency shelters and support services for domestic violence victims through 2026",
 "the Protecting Medicare and American Farmers from Sequester Cuts Act": "which delayed automatic Medicare payment cuts through March 2022 and eased other scheduled reductions",
 "which let people alleging sexual assault or harassment": "which let people alleging sexual assault or harassment take their claim to court despite a contract requiring private arbitration",
 "the Postal Service Reform Act": "the Postal Service Reform Act, which ended prefunding of retiree health benefits, tied postal retirees to Medicare and required six-day delivery",
 "which imposed entry bans on people from other countries": "which imposed entry bans on foreigners responsible for human rights abuses against people for their sexual orientation or gender identity",
 "the Honoring our PACT Act": "the Honoring our PACT Act, expanding health care and disability benefits for veterans exposed to burn pits and other toxins",
 "the CROWN Act": "the CROWN Act, barring discrimination based on hair texture or hairstyles associated with race in jobs, housing and education",
 "which required private health plans to cover diagnosis": "which required private health plans to cover diagnosis and treatment of birth defects and other conditions present at birth",
 "the Federal Firefighters Fairness Act": "the Federal Firefighters Fairness Act, presuming certain cancers and heart and lung conditions in federal firefighters came from the job",
 "the Rights for the TSA Workforce Act": "the Rights for the TSA Workforce Act, giving airport security screeners the same union and appeal rights as most federal workers",
 "the Community Services Block Grant Modernization Act": "which renewed through 2032 federal grants for local antipoverty services and raised the income eligibility threshold",
 "the Domestic Terrorism Prevention Act": "the Domestic Terrorism Prevention Act, creating domestic terrorism teams at the FBI, Justice Department and Homeland Security with regular threat reporting",
 "a bill to let injured federal workers": "a bill letting injured federal workers be treated by nurse practitioners and physician assistants under federal workers' compensation",
 "the Protecting Our Kids Act": "the Protecting Our Kids Act, raising the buying age for many semiautomatic rifles to 21 and banning new large-capacity magazines",
 "a bill to let federal courts temporarily take guns": "a bill letting federal courts temporarily take guns from someone found dangerous and funding state red flag laws",
 "the Recovering America's Wildlife Act": "the Recovering America's Wildlife Act, sending dedicated federal funding to states and tribes to conserve wildlife and plants most in need",
 "the Lower Food and Fuel Costs Act": "the Lower Food and Fuel Costs Act, which funded technology-guided farming, expanded biofuel infrastructure and strengthened oversight of meat markets",
 "the Active Shooter Alert Act": "the Active Shooter Alert Act, creating a national alert network to warn the public during an active shooter emergency",
 "the final Honoring our PACT Act": "the final Honoring our PACT Act, expanding health care and disability benefits for veterans exposed to burn pits and other toxins",
 "the National Defense Authorization Act for Fiscal Year 2023": "the National Defense Authorization Act for Fiscal Year 2023, which set defense policy and approved Defense Department programs and military construction",
 "the Women's Health Protection Act of 2022": "the Women's Health Protection Act of 2022, creating a federal right to abortion care after Roe v. Wade was overturned",
 "which barred states from interfering with a person's ability to travel": "which barred states from interfering with travel across state lines for abortion care or with anyone who helps",
 "the Right to Contraception Act": "the Right to Contraception Act, writing into federal law the right to obtain contraception and providers' right to supply it",
 "the Assault Weapons Ban of 2022": "the Assault Weapons Ban of 2022, criminalizing the sale, making or import of semiautomatic assault weapons and large capacity magazines",
 "the Wildfire Response and Drought Resiliency Act": "the Wildfire Response and Drought Resiliency Act, funding wildfire mitigation and drought planning and raising pay for federal wildland firefighters",
 "the Whistleblower Protection Improvement Act": "the Whistleblower Protection Improvement Act, strengthening protections for federal employees who report wrongdoing and barring retaliatory personnel actions",
 "the Presidential Election Reform Act": "the Presidential Election Reform Act, requiring electors be chosen under state law set before election day and narrowing grounds for objections",
 "the Break the Cycle of Violence Act": "the Break the Cycle of Violence Act, funding community violence intervention and job training in neighborhoods with high gun violence",
 "which funded state, local, and tribal investigators": "which funded state, local and tribal investigators and prosecutors to solve more murders and other violent crimes",
 "which made contract terms that bar sharing facts": "which made contract terms barring sharing facts or criticism unenforceable in sexual assault and sexual harassment cases",
 "the One Stop Shop Community Reentry Program Act": "the One Stop Shop Community Reentry Program Act, funding community organizations that help people leaving prison find housing and jobs",
 "the Veteran Service Recognition Act": "the Veteran Service Recognition Act, letting Homeland Security grant green cards to noncitizen military veterans facing deportation",
 "the Law Enforcement De-Escalation Training Act": "the Law Enforcement De-Escalation Training Act, funding police training to calm tense situations and respond to mental health crises",
 "the VA Employee Fairness Act": "the VA Employee Fairness Act, letting doctors and nurses at veterans' hospitals bargain and file grievances over patient care and pay",
 "the Born-Alive Abortion Survivors Protection Act, a bill to require medical care": "the Born-Alive Abortion Survivors Protection Act, requiring medical care for a child born alive after an attempted abortion",
 "which would block the next non-emergency release": "a bill to block the next non-emergency Strategic Petroleum Reserve release until officials planned more federal drilling leases",
 "which blocked the District of Columbia's rewritten criminal code": "which blocked the District of Columbia's rewritten criminal code, which lowered maximum sentences for carjacking and robbery",
 "which would expand oil, gas and mineral leasing": "a bill to expand oil, gas and mineral leasing on federal land, speed permits and repeal the methane fee",
 "the Secure the Border Act": "the Secure the Border Act, restarting border wall building, narrowing asylum and requiring employers to verify workers' legal status",
 "which would have cancelled the Education Department rule": "a resolution to cancel the Education Department rule pausing student loan payments and forgiving up to $20,000 per borrower",
 "the Schools Not Shelters Act": "the Schools Not Shelters Act, cutting federal funding to public schools and colleges that shelter immigrants who entered without admission",
 "which would block federal money from housing certain immigrants": "a bill to bar housing certain immigrants on federal land and cancel New York City's Floyd Bennett Field lease",
 "which would stop the EPA from carrying out its 2027-and-later": "a bill to stop the EPA's 2027-and-later vehicle emissions rule and limit tailpipe rules that reduce vehicle choice",
 "the 2024 defense policy law": "the 2024 defense policy law, setting Defense Department policy and approving its programs and military construction",
 "the Unlocking our Domestic LNG Potential Act": "the Unlocking our Domestic LNG Potential Act, ending Energy Department approval of gas exports, deemed in the public interest",
 "the Expanding Access to Capital Act": "the Expanding Access to Capital Act, a bill to loosen securities rules for smaller companies and widen access to private offerings",
 "the Restoring American Energy Dominance Act": "the Restoring American Energy Dominance Act, forcing the Bureau of Land Management to drop its proposed leasing rule",
 "the WEST Act": "the WEST Act, voiding the public lands rule that put conservation on equal footing with grazing and drilling",
 "the Protecting Access for Hunters and Anglers Act": "the Protecting Access for Hunters and Anglers Act, blocking federal land agencies from banning lead ammunition or fishing tackle",
 "the Trust the Science Act": "the Trust the Science Act, ordering the Interior Department to drop the gray wolf from the endangered species list",
 "which would cancel the 20-year mining ban": "a bill to cancel the 20-year mining ban near Minnesota's Boundary Waters and reissue cancelled mineral leases",
 "which would reissue cancelled Arctic Refuge oil and gas leases": "a bill to reissue cancelled Arctic Refuge oil and gas leases and order another coastal plain lease sale",
 "which would let mining claim holders": "a bill letting mining claim holders use federal land for roads and facilities without finding a valuable mineral deposit",
 "which would require federal officials to detain immigrants": "a bill to make federal officials detain immigrants lacking legal status who are charged with assaulting a police officer",
 "the LEOSA Reform Act": "the LEOSA Reform Act, letting qualified current and retired police carry concealed guns in school zones and national parks",
 "the Illegitimate Court Counteraction Act, a bill to sanction foreigners who help the International Criminal Court investigate": "the Illegitimate Court Counteraction Act, sanctioning foreigners who help the International Criminal Court prosecute Americans or allied citizens",
 "the House's fiscal year 2025 defense authorization bill": "the House's fiscal year 2025 defense authorization bill, setting Defense Department policy and raising junior enlisted pay",
 "the Refrigerator Freedom Act": "the Refrigerator Freedom Act, barring refrigerator and freezer efficiency standards unless found workable and not costlier for consumers",
 "which would make immigrants barred from entry or deportable": "a bill making immigrants deportable or barred from entry for stalking, child abuse, sex offenses or domestic violence",
 "a bill to deny certain federal immigration funds": "a bill denying certain federal immigration funds to states and localities that limit information sharing or ignore detention requests",
 "the Fix Our Forests Act, a bill to speed federal wildfire work": "the Fix Our Forests Act, speeding federal wildfire work by exempting many forest projects from environmental review",
 "the Liberty in Laundry Act": "the Liberty in Laundry Act, barring clothes washer efficiency rules unless found workable and unlikely to raise buyers' costs",
 "the Laken Riley Act, a bill to make federal officers": "the Laken Riley Act, making federal officers detain immigrants here unlawfully who are charged with theft or burglary",
 "the Illegitimate Court Counteraction Act, a bill to sanction foreigners who help the International Criminal Court pursue": "the Illegitimate Court Counteraction Act, sanctioning foreigners who help the International Criminal Court pursue Americans or allied citizens",
 "a bill to bar entry to and allow deportation": "a bill barring entry and allowing deportation of non-citizens for sex offenses, domestic violence, stalking or child abuse",
 "the Laken Riley Act, sending it to the president": "the Laken Riley Act, sending it to the president to require jailing immigrants here illegally who are arrested for theft",
 "the Fix Our Forests Act, a bill to speed tree-thinning": "the Fix Our Forests Act, speeding tree-thinning in high-risk wildfire zones on federal land by skipping full environmental review",
 "the Born-Alive Abortion Survivors Protection Act, a bill to require newborn care": "the Born-Alive Abortion Survivors Protection Act, requiring newborn care for a baby born alive after an attempted abortion",
 "the Agent Raul Gonzalez Officer Safety Act": "a bill making fleeing Border Patrol by vehicle near the border a crime punishable by prison",
 "the SAVE Act": "the SAVE Act, requiring paper proof of U.S. citizenship, such as a passport, to register to vote",
 "the TAKE IT DOWN Act": "the TAKE IT DOWN Act, which makes posting nonconsensual intimate images, including deepfakes, a crime and orders 48-hour takedowns",
 "which revoked the Clean Air Act waivers letting California enforce heavy-duty": "which revoked the Clean Air Act waivers letting California enforce its Advanced Clean Trucks and zero-emission fleet standards",
 "which revoked the Clean Air Act waiver letting California enforce its Omnibus": "which revoked the Clean Air Act waiver letting California enforce its Omnibus Low NOx limits on heavy-duty engine pollution",
 "which revoked the Clean Air Act waiver letting California enforce Advanced": "which revoked the Clean Air Act waiver letting California enforce Advanced Clean Cars II, its zero-emission new car rule",
 "the Save SBA from Sanctuary Cities Act": "the Save SBA from Sanctuary Cities Act, making the small-business agency move offices out of sanctuary areas within 60 days",
 "which would bar the District of Columbia from limiting": "a bill to bar the District of Columbia from limiting how its agencies share immigration information or honor federal detainers",
 "which would make drunk or drugged driving": "a bill making drunk or drugged driving grounds to bar an immigrant from entry or deport one already here",
 "which extended the 2017 income tax cuts": "which extended the 2017 tax cuts, cut Medicaid and food aid, and raised the debt limit",
 "the House defense policy bill for fiscal year 2026": "the House defense policy bill for fiscal year 2026, authorizing Defense Department and nuclear security funding",
 "the Stop Illegal Entry Act": "the Stop Illegal Entry Act, raising prison penalties for illegal entry and re-entry, up to life for serious criminals",
 "the DC CRIMES Act, a bill": "the DC CRIMES Act, limiting D.C. youth-offender sentencing to people under 18 and barring sentences below mandatory minimums",
 "which cancelled a federal plan change": "which cancelled a federal plan change that had ended new coal leasing in Wyoming's Powder River Basin",
 "which cancelled the 2024 decision closing": "which cancelled the 2024 decision closing about 1.2 million acres of the Arctic refuge to oil and gas leasing",
 "the PERMIT Act": "the PERMIT Act, speeding Clean Water Act permits, limiting states' power to block projects and dropping groundwater from protection",
 "the Protect America's Workforce Act": "the Protect America's Workforce Act, cancelling the March 2025 executive order that stripped union bargaining rights from most federal workers",
 "a bill to make federal energy regulators": "a bill making federal energy regulators the sole lead agency for gas pipeline reviews and ending states' water quality sign-off",
 "the Kayla Hamilton Act": "the Kayla Hamilton Act, requiring locked placement for immigrant children 12 and older with gang tattoos or criminal records",
 "which sets 2026 funding for the Commerce": "which sets 2026 funding for the Commerce, Justice, Science, Energy, Water, Interior and Environment parts of the budget",
 "which extends the larger Affordable Care Act premium tax credits": "which extends the larger Affordable Care Act premium tax credits through 2028, including for higher-earning households",
 "the Affordable HOMES Act": "the Affordable HOMES Act, cancelling Energy Department efficiency rules for manufactured housing and its power to issue similar rules",
 "the Flexibility for Workers Education Act": "the Flexibility for Workers Education Act, stopping certain voluntary training outside normal hours from counting as paid work time",
 "which sets 2026 funding for financial services": "which sets 2026 funding for financial services and general government agencies and the State Department",
 "the Protecting Prudent Investment of Retirement Savings Act": "which requires managers of workplace retirement plans to make investment choices on financial factors alone",
 "the Main Street Parity Act": "the Main Street Parity Act, lowering the down payment a small business must put up for SBA property loans",
 "a bill to let states spend federal welfare block grant money": "a bill letting states spend federal welfare block grant money on pregnancy centers that promote carrying to term",
 "which cancels the land order protecting": "which cancels the land order protecting about 225,504 acres of northeastern Minnesota national forest and reopens it to mineral leasing",
 "the Pregnant Students' Rights Act": "the Pregnant Students' Rights Act, making colleges that take federal student aid tell students about pregnant students' rights and resources",
 "the Ernest Peltz Accrued Veterans Benefits Act": "which sets out how Veterans Affairs pays a pension that was owed but unpaid when a veteran died",
 "the PROTECT Taiwan Act": "the PROTECT Taiwan Act, seeking China's exclusion from six international financial bodies if the President reports China threatening Taiwan",
 "the Undersea Cable Protection Act": "the Undersea Cable Protection Act, ending Commerce Department permits for undersea fiber optic cable work inside national marine sanctuaries",
 "the Law-Enforcement Innovate to De-Escalate Act": "which takes less-than-lethal projectile devices such as certain TASERs out of Gun Control Act regulation",
 "the Homeowner Energy Freedom Act": "the Homeowner Energy Freedom Act, repealing the Energy Department's home electrification rebates for lower-income households and contractor training grants",
 "the Tribal Trust Land Homeownership Act": "the Tribal Trust Land Homeownership Act, setting deadlines for the Bureau of Indian Affairs to process tribal land mortgages",
 "the Territorial Student Access to Higher Education Act": "which makes public colleges taking federal student aid charge in-state tuition to students from U.S. territories",
 "a bill to fund the Department of Homeland Security": "a bill funding Homeland Security for the rest of the year and ending the partial shutdown begun February 14, 2026",
 "the MAWS Act": "the MAWS Act, which has NOAA run a pilot program buying invasive blue catfish caught in the Chesapeake Bay watershed",
 "the Small Business Innovation and Economic Security Act": "which renews the federal small business research and technology transfer grant programs through 2031",
 "a bill to stop federal land agencies from banning": "a bill stopping federal land agencies from banning or regulating lead ammunition and fishing tackle on federal land",
 "the Deporting Fraudsters Act": "the Deporting Fraudsters Act, making public benefits fraud grounds to bar someone from entry or deport them",
 "the BOWOW Act": "the BOWOW Act, making harming a law enforcement working animal grounds to bar a non-citizen from entry or deport them",
 "the American Water Stewardship Act": "the American Water Stewardship Act, renewing EPA water quality and restoration programs through 2031, including the Great Lakes program",
 "a bill to set up a federal commission on crime and immigration": "a bill setting up a federal commission on crime and immigration in Washington, DC and a federal cleanup program there",
 "the Pay Our Homeland Defenders Act": "the Pay Our Homeland Defenders Act, funding Homeland Security and ending the partial shutdown that began February 14, 2026",
 "a bill to let the President bar from U.S. ports": "a bill letting the President bar ships that called at a port seized by a Western Hemisphere country",
 "the RED Tape Act": "the RED Tape Act, dropping the Clean Air Act requirement that the EPA review and comment on major federal projects",
 "which orders the Department of Homeland Security to grant Haitians": "which orders Homeland Security to grant Haitians temporary protected status for 18 months, shielding them from immigration detention",
 "which sets up an interagency team": "which sets up an interagency team to speed federal review of requests to run communications lines across federal land",
 "the Kari's Law Reporting Act": "the Kari's Law Reporting Act, making the FCC report on enforcing the rule that office phones allow direct 911 calls",
 "the Reliable Federal Infrastructure Act": "the Reliable Federal Infrastructure Act, repealing the standards phasing fossil fuel use out of new federal buildings by 2030",
 "the HEATS Act": "the HEATS Act, exempting geothermal drilling on state and private land from federal permits and environmental review",
 "the Clergy Act": "the Clergy Act, giving clergy a two-year window to undo their exemption from Social Security and Medicare taxes",
 "the 2026 farm bill": "the 2026 farm bill, renewing Agriculture Department crop support, conservation, food aid and rural development programs through 2031",
 "the Keeping Violent Offenders Off Our Streets Act": "which treats posting criminal and immigration bail bonds as insurance business under federal insurance-fraud law",
 "the Cashless Bail Reporting Act": "the Cashless Bail Reporting Act, making the Justice Department list yearly the governments releasing certain defendants without cash bail",
 "the Monitor Accountability Act": "the Monitor Accountability Act, setting conditions on appointing the independent monitors who oversee governments under court consent decrees",
 "the Military Construction, Veterans Affairs, and Related Agencies Appropriations Act, 2027": "the 2027 appropriations bill setting the year's funding for military construction and the Department of Veterans Affairs",
 "the PROTECT Kids Act": "the PROTECT Kids Act, requiring parental consent before federally funded elementary and middle schools change a student's gender on forms",
 "the Veterans 2nd Amendment Protection Act": "the Veterans 2nd Amendment Protection Act, barring Veterans Affairs from reporting certain veterans to the federal gun background check system",
 "which reauthorizes for seven years the Northwest Straits": "which reauthorizes for seven years the Northwest Straits Marine Conservation Initiative that protects and restores marine waters and habitats",
 "which adds penalties for states that misuse money": "which adds penalties for states that misuse the federal block grant helping low-income working families pay for child care",
 "the Ukraine Support Act": "the Ukraine Support Act, sending aid to Ukraine and certain European countries, setting up a reconstruction fund and penalizing Russia",
 "the TRUE Accountability Act": "the TRUE Accountability Act, making federal agencies write and follow plans to stop fraud and improper payments in disaster spending",
 "the Faster Labor Contracts Act": "the Faster Labor Contracts Act, setting deadlines for bargaining a first union contract and sending stalled talks to arbitration",
 "the No Aid for Ghost Students Act of 2026": "the No Aid for Ghost Students Act, making the Education Department screen every federal student aid application for identity fraud",
 "the Small Business Lending Fraud Prevention Act": "which makes Small Business Administration staff certify they have no conflict of interest before working on a loan",
 "the Financial Exploitation Prevention Act": "the Financial Exploitation Prevention Act, letting investment companies delay cashing out an account of a possibly exploited older investor",
 "which renews the federal Terrorism Risk Insurance Program": "which renews through 2034 the federal Terrorism Risk Insurance Program covering part of insurers' losses from a terrorist attack",
 "the Protecting Privacy in Purchases Act": "the Protecting Privacy in Purchases Act, barring payment card networks from using a merchant code that singles out gun retailers",
 "which reauthorizes through 2030 the federal program that pays for breast": "which reauthorizes through 2030 the federal program paying for breast and cervical cancer screening and treatment for low-income women",
 "the Value Over Cost Act": "the Value Over Cost Act, letting the General Services Administration award supply-schedule contracts on best value rather than lowest price",
 "the National Defense Authorization Act for Fiscal Year 2027": "the National Defense Authorization Act for Fiscal Year 2027, setting Defense Department policy, troop levels and equipment purchases",
 "the Stop Insider Trading Act": "the Stop Insider Trading Act, barring members of Congress and their spouses and dependent children from buying stocks",
 "the Continuing Appropriations and Extensions Act, 2027": "the 2027 stopgap funding law, keeping agencies at 2026 levels through December 11, 2026",
 "which cancelled the 2020 EPA rule that had dropped methane limits on new and rebuilt": "which cancelled the 2020 EPA rule that had dropped methane limits on new and rebuilt oil and gas sources",
 "the Infrastructure Investment and Jobs Act, a bipartisan deal": "the Infrastructure Investment and Jobs Act, a bipartisan deal putting roughly $1 trillion into roads, bridges, transit, broadband and water",
 "which would cancel the Justice and Homeland Security rule": "a resolution to cancel the rule letting asylum officers decide asylum claims directly instead of sending them to immigration court",
 "the Inflation Reduction Act, which let Medicare negotiate drug prices, capped insulin": "the Inflation Reduction Act, which let Medicare negotiate drug prices, capped Medicare insulin at $35 monthly and funded clean energy",
 "the Respect for Marriage Act": "the Respect for Marriage Act, making states honor valid same-sex and interracial marriages",
 "which would have repealed the 1991 and 2002 laws": "a bill to repeal the 1991 and 2002 Iraq war authorizations, ending the legal basis for military action there",
 "which would have extended and widened federal payments": "a bill extending and widening federal payments to people sickened by nuclear testing fallout, uranium mining and Manhattan Project waste",
 "which would have barred spending in 2024": "a bill barring 2024 spending to carry out EPA tailpipe pollution limits for 2027 and later cars and trucks",
 "which would end the April 2, 2025 emergency": "a resolution to end the April 2, 2025 emergency used to place a 10 percent tariff on most imports",
 "which cancelled an EPA rule requiring plants": "which cancelled an EPA rule requiring plants moving to a lower pollution category to keep controlling persistent toxic air pollutants",
 "the GENIUS Act, which set the first federal rules": "the GENIUS Act, setting the first federal rules for payment stablecoins, backed one-for-one by cash or safe assets",
 "the National Defense Authorization Act for Fiscal Year 2026, as amended": "the Senate's National Defense Authorization Act for Fiscal Year 2026, setting defense policy and authorizing Defense Department funding",
 "which would end the national emergency the President declared on July 30": "a resolution to end the July 30, 2025 emergency used to add a 40 percent tariff on many Brazilian imports",
 "the Lindsey O. Graham Sanctioning Russia and Iran Act": "the Sanctioning Russia and Iran Act of 2026, imposing sanctions and tariffs tied to Russia and extending Iran sanctions",
}
TRIM = {
 "the Consolidated Appropriations Act, 2026, which funds several federal departments for the rest of the budget year and became law": "the Consolidated Appropriations Act, 2026, which funds several federal departments and became law",
 "the Consolidated Appropriations Act, 2026, which funds several federal departments for the rest of the budget year and later became law": "the Consolidated Appropriations Act, 2026, funding several federal departments for the rest of the budget year, which later became law",
}
ROLL = {
 "house:117-1:72": {"yea": "Voted to send H.R. 1319, the American Rescue Plan Act, to the President: $1.9 trillion in COVID-19 relief with $1,400 payments. The House passed it 220-211."},
 "house:117-1:181": {"yea": "Voted for sending S.J.Res. 15 to the President to cancel the true lender rule, which let national banks front loans escaping state rate caps. The House passed it 218-208."},
 "house:117-1:183": {"yea": "Voted for sending S.J.Res. 13 to the President to cancel a rule giving employers the evidence behind a discrimination finding before settlement talks. The House passed it 219-210."},
 "house:117-1:185": {"yea": "Voted for sending S.J.Res. 14 to the President to cancel the 2020 EPA rule that had dropped methane limits on new oil and gas sources. The House passed it 229-191."},
 "house:117-1:369": {"yea": "Voted to send H.R. 3684, the Infrastructure Investment and Jobs Act, to the President: roughly $1 trillion for roads, bridges, transit, broadband and water. The House passed it 228-206."},
 "house:117-2:9": {"yea": "Voted to pass the Freedom to Vote: John R. Lewis Act, a bill to expand early and mail voting and restore the Voting Rights Act. The House sent it to the Senate 220-203. The Senate never passed it."},
 "house:117-2:299": {"yea": "Voted for final House passage of the Bipartisan Safer Communities Act, which widened background checks for buyers under 21 and closed the dating-partner gun loophole. The House agreed 234-193 and it became Public Law 117-159."},
 "house:117-2:404": {"yea": "Voted for final House passage of the CHIPS and Science Act, which put about $52 billion into U.S. semiconductor manufacturing and research. The House agreed 243-187 and it became Public Law 117-167."},
 "house:117-2:420": {"yea": "Voted to send H.R. 5376, the Inflation Reduction Act, to the President: Medicare drug price negotiation, a $35 insulin cap and clean energy credits. The House passed it 220-207."},
 "house:117-2:506": {"yea": "Voted for final House passage of the SBA Cyber Awareness Act, which makes the Small Business Administration report yearly on its cybersecurity and any breach. The House agreed 417-0 and it became Public Law 117-259."},
 "house:117-2:511": {"yea": "Voted for final House passage of the Patents for Humanity Act of 2022, which speeds patent proceedings for inventors solving humanitarian problems. The House agreed 396-24 and it became Public Law 117-245."},
 "house:117-2:513": {"yea": "Voted for sending H.R. 8404, the Respect for Marriage Act, to the President: it made states recognize valid same-sex and interracial marriages. The House passed it 258-169, and it became law."},
 "house:117-2:523": {"yea": "Voted for the Further Continuing Appropriations and Extensions Act, 2023, a stopgap that kept federal agencies funded to December 23, 2022. The House agreed 224-201 and it became Public Law 117-229."},
 "house:118-1:268": {"yea": "Voted to pass H.R. 1640, the Save Our Gas Stoves Act, a bill to block the Energy Department's efficiency rule for kitchen ranges and ovens. The House passed it 249-181, but the Senate never voted, so the bill died."},
 "house:118-1:690": {"yea": "Voted to send S.J.Res. 32 to the President to cancel the consumer bureau rule making lenders report small-business loan data, including loans to minority-owned firms. The House passed it 221-202, but the President vetoed it and the Senate override failed, so the rule stayed."},
 "house:118-2:10": {"yea": "Voted to pass H.J.Res. 98 by 206-177, a resolution cancelling a labor board rule that eased treating franchise chains and owners as joint employers. The Senate agreed, but the president vetoed it on May 3, 2024, and the House override failed."},
 "house:118-2:25": {"yea": "Voted to pass H.R. 5585, a bill making fleeing Border Patrol by vehicle near the border a crime punishable by prison. The House passed it 271-154, but the bill died when that Congress ended."},
 "house:118-2:93": {"yea": "Voted to pass H.R. 1121, the Protecting American Energy Production Act, a bill to bar any President from halting fracking without approval from Congress. The House passed it 229-188, but the Senate never acted, so it did not become law.", "nay": "Voted against passing H.R. 1121, the Protecting American Energy Production Act, a bill to bar any President from halting fracking without approval from Congress. The House passed it 229-188, but the Senate never acted, so it did not become law."},
 "house:118-2:184": {"yea": "Voted to pass H.R. 6192, a bill to end the Energy Department's duty to keep tightening home appliance efficiency rules. The House passed it 212-195, but the Senate never acted and the bill died.", "nay": "Voted against passing H.R. 6192, a bill to end the Energy Department's duty to keep tightening home appliance efficiency rules. The House passed it 212-195, but the Senate never acted and the bill died."},
 "house:118-2:201": {"yea": "Voted to pass H.R. 7530, the DC CRIMES Act, a bill to cut DC's youth offender age from 24 to 18 and freeze existing sentences. The House passed it 225-181, but the Senate never acted and it died.", "nay": "Voted against passing H.R. 7530, the DC CRIMES Act, a bill to cut DC's youth offender age from 24 to 18 and freeze existing sentences. The House passed it 225-181, but the Senate never acted and it died."},
 "house:118-2:230": {"yea": "Voted to pass H.R. 5403, the CBDC Anti-Surveillance State Act, a bill to bar the Federal Reserve from issuing a digital dollar or individual accounts. The House passed it 216-192, but the Senate never took it up, so the bill died.", "nay": "Voted against passing H.R. 5403, the CBDC Anti-Surveillance State Act, a bill to bar the Federal Reserve from issuing a digital dollar or individual accounts. The House passed it 216-192, but the Senate never took it up, so the bill died."},
 "house:118-2:232": {"yea": "Voted to pass H.R. 192, a bill to bar noncitizens from voting in District of Columbia elections by repealing the 2022 DC law allowing it. The House passed it 262-143, but the Senate never acted and the bill died.", "nay": "Voted against passing H.R. 192, a bill to bar noncitizens from voting in District of Columbia elections by repealing the 2022 DC law allowing it. The House passed it 262-143, but the Senate never acted and the bill died."},
 "house:118-2:500": {"yea": "Voted for final House passage of the fiscal year 2025 National Defense Authorization Act, which sets military policy and spending and raises junior enlisted pay. The House agreed 281-140 and it became Public Law 118-159."},
 "house:119-1:61": {"yea": "Voted to pass S.J.Res. 11, canceling the new rule that made offshore oil and gas companies list possible shipwrecks in their drilling plans. The House passed it 221-202, and it became law."},
 "house:119-1:95": {"yea": "Voted to pass S.J.Res. 28, 219-211, sending it to the President to repeal the rule that put the largest digital payment apps under federal supervision. It was signed on May 9, 2025 as Public Law 119-11."},
 "house:119-1:96": {"yea": "Voted to pass S.J.Res. 18, sending it to the President to repeal the consumer bureau rule limiting overdraft fees at very large banks to $5. The House passed it 217-211, and it became Public Law 119-10 on May 9, 2025.", "nay": "Voted against passing S.J.Res. 18, sending it to the President to repeal the consumer bureau rule limiting overdraft fees at very large banks to $5. The House passed it 217-211, and it became Public Law 119-10 on May 9, 2025."},
 "house:119-1:110": {"yea": "Voted to pass H.J.Res. 60 by 219-205, cancelling the National Park Service rule that closed an off-road route and shoreline driving areas at Lake Powell. It became law on May 23, 2025 (Public Law 119-13)."},
 "house:119-1:128": {"yea": "Voted to pass H.R. 2243, the LEOSA Reform Act, letting qualified working and retired police carry concealed guns in school zones and national parks. The House passed it 229-193, but the Senate has not acted, so it is not law."},
 "house:119-1:143": {"yea": "Voted to send S.J.Res. 31 to the President, canceling the EPA rule keeping toxic air pollutant controls on plants moving to a lower category. The House passed it 216-212, and it became law on June 20, 2025 (Public Law 119-20)."},
 "house:119-1:200": {"yea": "Voted to pass S. 1582, the GENIUS Act, setting federal rules for payment stablecoins, digital tokens meant to hold a steady value. Only approved banks and licensed issuers may issue them, backed one-for-one by reserves. The House passed it 308-122 and it became Public Law 119-27 on July 18, 2025.", "nay": "Voted against passing S. 1582, the GENIUS Act, setting federal rules for payment stablecoins, digital tokens meant to hold a steady value. Only approved banks and licensed issuers may issue them, backed one-for-one by reserves. The House passed it 308-122 and it became Public Law 119-27 on July 18, 2025."},
 "house:119-1:224": {"yea": "Voted for H.J.Res. 104 to cancel the federal land plan for the Miles City field office in eastern Montana, reopening those lands to coal leasing. The House passed it 211-208."},
 "house:119-1:285": {"yea": "Voted to accept the Senate's version of H.R. 5371, the funding bill ending the 43-day shutdown and funding most agencies into January 2026. The House agreed 222-209, and it became Public Law 119-37 on November 12, 2025."},
 "house:119-1:296": {"yea": "Voted to send S.J.Res. 80 to the President, cancelling the 2022 plan that closed about 48% of the National Petroleum Reserve in Alaska to drilling. The House passed it 216-209, and it became Public Law 119-47 on December 5, 2025."},
 "house:119-1:320": {"yea": "Voted to pass the National Defense Authorization Act for Fiscal Year 2026, placed into S. 1071, setting defense policy and Defense Department spending. The House passed it 312-112, the Senate agreed, and it became Public Law 119-60 on December 18, 2025."},
 "house:119-1:360": {"yea": "Voted yes on H.R. 845, a bill ordering the Interior Department to drop the gray wolf from the endangered species list, beyond court review. The House passed it 211-204; the bill is in a Senate committee and has not become law."},
 "house:119-2:69": {"yea": "Voted to pass S. 1383 as rewritten by the House into the SAVE America Act, requiring citizenship proof to register and photo ID to vote. It passed the House 218-213."},
 "house:119-2:95": {"yea": "Voted for H.J.Res. 139, a proposed constitutional amendment capping yearly federal spending at the prior three years' average revenue, adjusted for population and inflation. It failed the House 211-207, short of the two-thirds majority needed."},
 "house:119-2:221": {"yea": "Voted to extend until July 2, 2026 the foreign intelligence surveillance authorities in Title VII of FISA, covering surveillance of targets outside the United States. It failed the House 198-218, short of the two-thirds majority needed."},
 "house:119-2:293": {"yea": "Voted for H.J.Res. 1, a proposed constitutional amendment requiring the Supreme Court to have nine justices, one chief justice and eight associate justices. It failed the House 212-206, short of the two-thirds majority needed."},
 "senate:117-1:110": {"yea": "Voted to pass the Senate's version of H.R. 1319, the American Rescue Plan Act, $1.9 trillion in COVID-19 relief with $1,400 payments. The Senate approved it 50-49, the House agreed, and it became Public Law 117-2 on March 11, 2021."},
 "senate:118-1:79": {"yea": "Voted to pass H.J.Res. 27, 53-43, using the Congressional Review Act to repeal the rule defining which streams and wetlands the Clean Water Act protects. The President vetoed it, and the House override attempt failed, so the rule stayed in place."},
 "senate:118-1:130": {"yea": "Voted to pass S.J.Res. 18, 50-47, to wipe out the 2022 rule narrowing when using benefits like Medicaid counts against green card seekers. The House never voted on it, so the 2022 rule stayed in place."},
 "senate:119-1:92": {"yea": "Voted to pass S.J.Res. 11, 54-44, using the Congressional Review Act to repeal the rule requiring an archaeology report with offshore oil and gas plans. It was signed on March 14, 2025 as Public Law 119-3, so the rule is gone."},
 "senate:119-1:97": {"yea": "Voted to pass H.J.Res. 35 by 52-47, wiping out the EPA rule that carried out the methane waste emissions charge on oil and gas sites. The measure became law on March 14, 2025 (Public Law 119-2).", "nay": "Voted against passing H.J.Res. 35 by 52-47, wiping out the EPA rule that carried out the methane waste emissions charge on oil and gas sites. The measure became law on March 14, 2025 (Public Law 119-2)."},
 "senate:119-1:106": {"yea": "Voted to pass S.J.Res. 28 by 51-47, cancelling the Consumer Financial Protection Bureau rule that put the largest digital payment apps under its supervision. It became law on May 9, 2025 (Public Law 119-11)."},
 "senate:119-1:151": {"yea": "Voted to send H.J.Res. 25 to the President, canceling the IRS rule that made services helping people sell digital assets report the sale proceeds. The Senate passed it 70-28, and it became law on April 10, 2025 (Public Law 119-5)."},
 "senate:119-1:239": {"yea": "Voted to pass H.J.Res. 60, sending it to the President: it repealed the National Park Service rule tightening off-road vehicle limits around Lake Powell. The Senate passed it 50-43, and it was signed on May 23, 2025 as Public Law 119-13."},
 "senate:119-1:372": {"yea": "Voted to pass the Senate's version of H.R. 1, extending the 2017 income tax cuts, cutting Medicaid and food aid, and raising the debt limit. Senators split 50-50 and the Vice President broke the tie. The House then agreed, and it became Public Law 119-21 on July 4, 2025."},
 "senate:119-1:598": {"yea": "Voted to pass S.J.Res. 77, a resolution to end the February 1, 2025 national emergency behind a 25% tariff on most Canadian imports. The Senate passed it 50-46, but the House never took it up, so the tariffs stayed in place."},
 "senate:119-1:618": {"yea": "Voted to pass H.R. 5371, the funding bill that ended the 43-day government shutdown. It paid for most agencies through January 30, 2026 and funded agriculture, military construction and veterans, and Congress for the full year. The Senate passed it 60-40 and it became law November 12, 2025 (Public Law 119-37).", "nay": "Voted against passing H.R. 5371, the funding bill that ended the 43-day government shutdown. It paid for most agencies through January 30, 2026 and funded agriculture, military construction and veterans, and Congress for the full year. The Senate passed it 60-40 and it became law November 12, 2025 (Public Law 119-37)."},
 "senate:119-1:632": {"yea": "Voted for sending H.J.Res. 131 to the President, cancelling the decision that limited oil and gas leasing in the Arctic National Wildlife Refuge. The Senate passed it 49-45."},
}
