TRIMP = {
 "which requires the state to serve every family": "which requires the state to serve every family on the child welfare housing assistance waiting list",
 "which lets workers use paid sick leave": "which lets workers use paid sick leave for their own or a family member's immigration hearing",
 "which bars employers from rejecting everyone with a criminal record": "which bars employers rejecting everyone with a criminal record or checking records before a conditional job offer",
 "which ends coroner authority": "which ends coroner authority over abortion and stillbirth deaths and decriminalizes concealing a birth",
 "a state layoff notice law": "which requires employers of 50 or more to give 60 days' notice of mass layoffs",
 "the Healthy Starts Act": "which makes employers pay for breast milk pumping breaks and widens rights for pregnant workers",
 "which bars employers from using immigration threats": "which bars employers using immigration threats to stop workers claiming wage and labor rights, with fines up to $10,000",
 "which defines what a personnel file includes": "which defines personnel files and makes employers give workers a free copy within 21 days",
 "a bill to cut Apple Health coverage": "a bill cutting Apple Health coverage after pregnancy from 12 months to six for people approved from July 2026",
 "which stops the state clawing back": "which stops the state clawing back disability cash aid when federal disability payments later cover the same months",
 "which passes all current child support": "which passes all current child support to families on cash welfare instead of the state keeping most of it",
 "which makes ride-hailing companies show drivers any bonus": "which makes ride-hailing companies show drivers per-trip bonuses and give 24 months of trip receipts",
 "which makes a hate crime provable": "which makes a hate crime provable when bias was part, not all, of the motive",
 "which lets workers take paid family leave in four-hour blocks": "which allows paid family leave in four-hour blocks and extends job protection to smaller employers",
 "which speeds up the required cuts in carbon pollution": "which speeds up required carbon pollution cuts from transportation fuels under the clean fuels program",
 "which requires state approval of every landfill permit": "which requires state approval of every landfill permit and renewal, beyond local health permits",
 "which requires a permit, with fingerprints": "which requires a permit, with fingerprints and a safety course, to buy a firearm",
 "which makes cities allow denser housing": "which makes cities allow denser housing within walking distance of rail and rapid bus stations",
 "a bill to make large data centers buy power": "a bill making large data centers use rate plans that protect other customers and 80% new renewable power",
 "a bill to make private jails and detention centers": "a bill making private jails and detention centers report deaths, abuse claims and injuries within a business day",
 "a bill to keep birth dates, home addresses": "a bill keeping birth dates, home addresses, location data and ID numbers held by agencies out of public records",
 "a bill to presume a driver careless": "a bill presuming a driver careless for hitting a pedestrian or cyclist in a crosswalk, bike lane or sidewalk",
 "which makes counties send voter list data requests": "which sends voter list requests to the Secretary of State and makes leaks a felony",
 "which makes cities and counties allow shelters": "which makes local governments allow shelters and supportive housing wherever homes or hotels are allowed",
 "which requires 60 days' notice to the Attorney General": "which requires 60 days' notice to the Attorney General before more health care mergers",
 "which extends Washington's bans on making illegal guns": "which extends Washington's illegal-gun manufacturing bans to 3D printers, milling machines and their digital files",
 "which sets a separate legal test": "which sets a separate legal test for claims that a local rule hinders minority voting",
 "which creates a statewide program to help low-income households": "which creates a statewide program of utility bill credits for low-income households",
 "which makes the Attorney General keep a list": "which makes the Attorney General list local governments with a recent record of voting bias",
 "which lets cities and counties set up land banks": "which lets cities and counties set up land banks holding land for affordable housing",
 "which makes employers tell workers within five days": "which makes employers tell workers within five days when federal agents seek employment records",
 "which makes companion chatbot companies tell users": "which makes companion chatbot companies disclose they are artificial intelligence and protect children",
 "which limits school restraint and isolation": "which limits school restraint and isolation to cases of real risk of serious harm",
 "which requires hospitals to treat pregnancy emergencies": "which requires hospitals to treat pregnancy emergencies to the standard of care, including abortion when that is the treatment",
 "a bill to set rules for searching transgender": "a bill setting rules for searching transgender and intersex people in local jails, barring searches to learn genital status",
 "a bill to bar social media apps": "a bill barring social media apps from showing addictive feeds to minors and limiting late-night notifications to them",
 "a bill to let the state sell up to $7 billion": "a bill letting the state sell up to $7 billion in highway bonds repaid from fuel taxes and fees",
 "which widens who counts as an isolated worker": "which widens who counts as an isolated worker entitled to a panic button and harassment training",
 "which caps how much off-street parking": "which caps required off-street parking, with none for affordable and senior housing",
 "which bars landlords from making tenants give up": "which bars landlords making tenants waive the right to sue or sign lease nondisclosure agreements",
 "which lets the state keep housing aid flowing": "which keeps state housing aid for elderly or disabled adults who move onto Social Security",
 "which raises the amount in a debtor's bank account": "which raises the bank balance a debtor can shield from creditors from $1,000 to $2,000",
 "which requires movie theaters to offer closed captioning": "which makes theaters offer closed captioning devices and larger chains run open-caption showings",
 "which makes companies that sell packaging and paper": "which makes companies selling packaging and paper in Washington pay for a statewide recycling program",
 "which caps what state and school employee health plans": "which caps public employee health plan payments to hospitals at 200% of Medicare from 2027",
 "which opens the state's foreclosure mediation program": "which opens state foreclosure mediation to condo and homeowner association members behind on dues",
 "a bill to let the Insurance Commissioner": "a bill letting the Insurance Commissioner order insurers to repay people they harmed and raising fines to $10,000",
 "a bill to bar schools from disciplining students": "a bill barring schools from disciplining students on automated scores alone or tracking them with facial recognition",
 "a bill to make companion chatbot apps": "a bill making companion chatbot apps disclose they are artificial intelligence and protect minors from harmful content",
 "a bill to make public works contracts": "a bill making public works contracts raise minimum hourly wages each year to match the latest prevailing wage",
 "a bill to create a state board to design a health plan": "a bill creating a state board to design a health plan covering all medically needed care for every resident",
 "a bill to extend the real estate excise tax exemption": "a bill extending the real estate excise tax exemption to affordable homes sold to low-income households by approved groups",
 "which lets prisons and jails hire": "which lets prisons and jails hire any legal U.S. worker as a corrections officer",
 "which bars drug makers from blocking delivery": "which bars drug makers blocking delivery of discounted 340B medicines to clinics serving low-income patients",
 "which lets the Attorney General demand documents": "which lets the Attorney General demand documents and sworn statements before suing over rights violations",
 "which bars police, including federal officers, from wearing face masks": "which bars police, including federal officers, from wearing face masks while dealing with the public",
 "which makes it easier for people wrongly convicted": "which makes it easier for people wrongly convicted of a felony to win state compensation",
 "which sets the state's first limits on automated license plate readers": "which sets the first state limits on automated license plate readers, allowing only listed uses",
 "which makes cities and counties of 30,000 or more": "which makes local governments of 30,000 or more allow homes on commercial or mixed-use land",
 "which creates a 9.9% state income tax": "which creates a 9.9% state income tax on individual income above $1 million from 2028",
}
ROLL = {1555829: {"yea": "Voted to pass House Bill 1232 after the Senate dropped its own changes, which tightens health and safety rules for private detention facilities. The Washington Senate approved it 29-19."}}
