// GENERATED by `npm run embed:pilot-manifest` in backend/ — do not edit by hand.
// Source: backend/manual-research/major-cities/embed-pilot.json plus the
// district ids resolved from the database at generation time.

export type EmbedPilotCity = {
  slug: string;
  name: string;
  state: string;
  election_date: string;
  review_date: string;
  official_source_url: string;
  enabled: boolean;
  /** city = every race that touches the city; state = statewide races only. */
  kind: "city" | "state";
  district_ids: string[];
};

export const EMBED_PILOT_PUBLISHERS: readonly string[] = [];

export const EMBED_PILOT_CITIES: Readonly<Record<string, EmbedPilotCity>> = {};
